stages:
  - test
  - publish
  - veracode scan
  - deps scan
  - generate pages

variables:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: libats_slick
  MYSQL_PASSWORD: libats_slick
  MYSQL_DATABASE: libats_slick
  DB_URL: jdbc:mariadb://mariadb:3306/libats_slick
  KAFKA_HOST: kafka:9092
  KAFKA_ZOOKEEPER_CONNECT: kafka:2181
  VAULT_ADDR: "http://vault.sit-ota.aws.in.here.com"

services:
  - name: mariadb:10.2
    command: ["mysqld", "--character-set-server=utf8", "--collation-server=utf8_unicode_ci", "--max_connections=1000"]
  - name: spotify/kafka
    alias: kafka

test:
  image: advancedtelematic/gitlab-jobs:0.2.3
  stage: test
  before_script:
    - mysql --protocol=TCP --host=mariadb --user=root --port 3306 -proot -e \ GRANT\ ALL\ PRIVILEGES\ ON\ \`libats_slick%\`.\*\ TO\ \'libats_slick\'@\'%\'\;
  script:
    - sbt -sbt-dir ./.sbt -ivy ./.ivy2 clean coverage test coverageReport sonarScan
  cache:
    paths:
      - .ivy2/
      - .sbt

publish:
  stage: publish
  tags:
    - docker-sock
  image: advancedtelematic/gitlab-jobs:0.2.3
  only:
    - master
  except:
    - schedules
  script:
    - git fetch origin
    - git describe
    - export VAULT_TOKEN=$(cat /opt/vault/token)
    - gitlab-docker-login $VAULT_ADDR
    - eval $(set-vault-env -v $VAULT_ADDR --secret gitlab/ats-aws-key --secret gitlab/maven-publish)
    - sbt -sbt-dir ./.sbt -ivy ./.ivy2 +publish
  cache:
    paths:
      - .ivy2/
      - .sbt/

veracode scan:
  # prepare and submit for static code analysis
  stage: veracode scan
  only:
    refs:
      - schedules
    variables:
      - $VERACODE_API_ID
  image: advancedtelematic/veracode:0.1.2
  before_script:
    - ./sbt package
  script:
    - run-veracode.sh
  artifacts:
    paths:
      - /tmp/package.zip

deps scan:
  # perform dependencies CVE analysis
  stage: deps scan
  only:
    - schedules
  image: advancedtelematic/gitlab-jobs:0.2.0
  script:
    - ./sbt dependencyCheckAggregate
    - mv target/scala-*/dependency-check-report.html ./depchk.html
  artifacts:
    paths:
      - depchk.html

pages:
  stage: generate pages
  only:
    - schedules
  dependencies:
    - deps scan
  script:
    - mkdir -p public
    - mv depchk.html public/index.html
  artifacts:
    paths:
      - public
    expire_in: 64 days
